//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/MainInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MainInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MainInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MainInput"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""9e1e6eec-7ef2-4f78-9f1f-99554244f6e9"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""789b633f-c139-4cc3-918c-7291fb52e0fe"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""f3565eae-929e-4df1-8973-57768a6470c9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""PassThrough"",
                    ""id"": ""e49fadf8-7bc5-43ff-92c4-0439f5c469d1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""46a50604-d7bd-449a-be20-8e035a75471f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Value"",
                    ""id"": ""3747b9e4-05ff-4696-ae15-aa5da4cdc443"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Walk"",
                    ""type"": ""Button"",
                    ""id"": ""db814724-c2c9-4272-be7b-664cd3f93018"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""7de345e8-8392-4171-89de-4281d053e2b3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FreeLook"",
                    ""type"": ""Button"",
                    ""id"": ""5b73df27-b665-46d7-8e09-b4e601222a78"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Alpha1"",
                    ""type"": ""Button"",
                    ""id"": ""8ce5fd18-6da7-49d6-8d92-4b077e42707d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Alpha2"",
                    ""type"": ""Button"",
                    ""id"": ""501be992-d9a5-4f05-a569-2f80dc0ab1c7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Alpha3"",
                    ""type"": ""Button"",
                    ""id"": ""7a5d21b1-ff1c-467a-81bd-5079780d8fe0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Alpha4"",
                    ""type"": ""Button"",
                    ""id"": ""bb5cd7a2-c5a6-407d-b4e7-678bf2c08257"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Alpha5"",
                    ""type"": ""Button"",
                    ""id"": ""4cf5e5d0-295b-4f83-a731-1baff25f10d6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Alpha6"",
                    ""type"": ""Button"",
                    ""id"": ""35a8485f-fbf0-4be3-ba19-b591ea26ec14"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Inventory"",
                    ""type"": ""Button"",
                    ""id"": ""d4f9843d-5888-4a0d-97a2-afed66df96a1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AutoRun"",
                    ""type"": ""Button"",
                    ""id"": ""19a9803c-a1b5-416d-93e2-58d34e011400"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FastWeaponTake"",
                    ""type"": ""Button"",
                    ""id"": ""959ffb3f-d83a-4c55-8546-6554e946c67b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FreeCursor"",
                    ""type"": ""Button"",
                    ""id"": ""2267da3a-eae0-4006-a56e-c3ac6b9cca99"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActiveAction"",
                    ""type"": ""Button"",
                    ""id"": ""ad96d2d3-4ef4-44e0-a5dd-b07cf35059e6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkillList"",
                    ""type"": ""Button"",
                    ""id"": ""a90bdd2a-bd4b-4cf0-9f5b-17ab268c8c08"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skill 1"",
                    ""type"": ""Button"",
                    ""id"": ""7ef8025b-8267-4d80-893b-6315ed5dc75f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skill 2"",
                    ""type"": ""Button"",
                    ""id"": ""d08887d1-5600-457a-b65d-d54fb644c12b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skill 3"",
                    ""type"": ""Button"",
                    ""id"": ""79054fbf-5e5d-4f6b-b120-7fb33443342c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Stats"",
                    ""type"": ""Button"",
                    ""id"": ""c5cd9414-8005-4d14-be67-dde2070c0d06"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""32f9fca5-b711-4982-9321-1d93ed675fb3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pose0"",
                    ""type"": ""Button"",
                    ""id"": ""6713b11e-1221-4040-b641-bcce60278a3f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pose1"",
                    ""type"": ""Button"",
                    ""id"": ""22cee51c-c374-47ef-88e2-93c9a1092e26"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pose2"",
                    ""type"": ""Button"",
                    ""id"": ""3b61dfaa-823d-4def-99b6-0cba6eb4f753"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""13f3b707-05fc-4750-93b7-1ecaf0fe262a"",
                    ""path"": ""2DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""13042378-326f-4848-9437-4b0469e6e1e0"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""6a87c2c6-4802-4946-888c-6ecc4e058e35"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e8d84b83-e26e-4617-8aed-b49a691547cf"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b465a408-da0b-4d82-8f2e-4e743088d3e1"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""81611ddc-b057-4f93-9158-731a81296794"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""165b0fae-d2d8-4148-84de-f74d2440e3a3"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cdc69bdb-1964-4996-bb1d-5fee986ac476"",
                    ""path"": ""<Pointer>/delta"",
                    ""interactions"": """",
                    ""processors"": ""InvertVector2(invertX=false),ScaleVector2(x=0.05,y=0.05)"",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d33e920f-404d-4ec9-a077-be56c293cc42"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(y=0.001)"",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""66b19777-de46-4bfa-9fff-1a872ea8cfab"",
                    ""path"": ""<Keyboard>/capsLock"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0208d4f0-a16b-4aa0-8508-db8bca98bfa6"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb46acc2-5bc4-4f24-a47c-2e37a51abdb5"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FreeLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9ad64d0a-a405-4133-9df5-f0680c917716"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Alpha1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d61878d5-0472-435b-b0e0-88f50cab2538"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Alpha2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0462a9e5-bedb-4010-8f05-8a467d4babd6"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Alpha3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2b8b86f5-2214-4b43-825c-83cb966e0169"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Alpha4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9ae5293c-aae1-4785-9a01-1a25631c425b"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Alpha5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5dfefe1d-39fe-41f8-ab8d-05a3754121d5"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Alpha6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e90d87ba-efb8-4f79-ac43-b820c0789f35"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a97490ec-847f-4f37-a89d-fa4177a94f4b"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AutoRun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c7ebc1fe-cc58-47d1-a2cd-a770e59abf16"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastWeaponTake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""55105597-4ce6-4de3-9a2c-cedddc3fbac8"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FreeCursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ff0cacd3-eccc-4274-8d90-62171f3fcadd"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActiveAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cff9e439-65d9-4730-94a0-07a6695958f1"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skill 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""23260931-ca30-4d72-b4f9-7487fbaafa90"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skill 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dd7ac05c-0b52-4d86-9527-d74d3012952d"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skill 3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b13cdb11-e680-4908-ab99-289210d1513f"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillList"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b912eda0-ec4d-4273-9fa7-90cc7d29bc49"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stats"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f0e6e662-6cef-4a3a-9024-37cbdcef3f6f"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""d61071ea-580a-4e18-9a74-6a011b33541a"",
                    ""path"": ""OneModifier(overrideModifiersNeedToBePressedFirst=true)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pose0"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""9cfddf62-d897-417e-97bf-3d186a6a5596"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pose0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""812ce5e3-9827-4f5e-a0cd-240f0ff9c537"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pose0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""969e3edc-d245-4bac-8783-ba64a91abc2a"",
                    ""path"": ""OneModifier(overrideModifiersNeedToBePressedFirst=true)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pose1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""4bdc9a56-3773-4fc5-aa6b-21f3a4f9d53e"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pose1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""864569dc-af1a-4fed-9dda-289c674efb5b"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pose1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""4d01a3a8-1b3f-4891-8f4c-184b3122c978"",
                    ""path"": ""OneModifier(overrideModifiersNeedToBePressedFirst=true)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pose2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""99675835-fd3b-4971-a7bf-deb5f634bcd3"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pose2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""366a994d-2a5d-4030-a5fd-475ba5c901db"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pose2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_Sprint = m_Player.FindAction("Sprint", throwIfNotFound: true);
        m_Player_Look = m_Player.FindAction("Look", throwIfNotFound: true);
        m_Player_Zoom = m_Player.FindAction("Zoom", throwIfNotFound: true);
        m_Player_Walk = m_Player.FindAction("Walk", throwIfNotFound: true);
        m_Player_Dash = m_Player.FindAction("Dash", throwIfNotFound: true);
        m_Player_FreeLook = m_Player.FindAction("FreeLook", throwIfNotFound: true);
        m_Player_Alpha1 = m_Player.FindAction("Alpha1", throwIfNotFound: true);
        m_Player_Alpha2 = m_Player.FindAction("Alpha2", throwIfNotFound: true);
        m_Player_Alpha3 = m_Player.FindAction("Alpha3", throwIfNotFound: true);
        m_Player_Alpha4 = m_Player.FindAction("Alpha4", throwIfNotFound: true);
        m_Player_Alpha5 = m_Player.FindAction("Alpha5", throwIfNotFound: true);
        m_Player_Alpha6 = m_Player.FindAction("Alpha6", throwIfNotFound: true);
        m_Player_Inventory = m_Player.FindAction("Inventory", throwIfNotFound: true);
        m_Player_AutoRun = m_Player.FindAction("AutoRun", throwIfNotFound: true);
        m_Player_FastWeaponTake = m_Player.FindAction("FastWeaponTake", throwIfNotFound: true);
        m_Player_FreeCursor = m_Player.FindAction("FreeCursor", throwIfNotFound: true);
        m_Player_ActiveAction = m_Player.FindAction("ActiveAction", throwIfNotFound: true);
        m_Player_SkillList = m_Player.FindAction("SkillList", throwIfNotFound: true);
        m_Player_Skill1 = m_Player.FindAction("Skill 1", throwIfNotFound: true);
        m_Player_Skill2 = m_Player.FindAction("Skill 2", throwIfNotFound: true);
        m_Player_Skill3 = m_Player.FindAction("Skill 3", throwIfNotFound: true);
        m_Player_Stats = m_Player.FindAction("Stats", throwIfNotFound: true);
        m_Player_Attack = m_Player.FindAction("Attack", throwIfNotFound: true);
        m_Player_Pose0 = m_Player.FindAction("Pose0", throwIfNotFound: true);
        m_Player_Pose1 = m_Player.FindAction("Pose1", throwIfNotFound: true);
        m_Player_Pose2 = m_Player.FindAction("Pose2", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_Sprint;
    private readonly InputAction m_Player_Look;
    private readonly InputAction m_Player_Zoom;
    private readonly InputAction m_Player_Walk;
    private readonly InputAction m_Player_Dash;
    private readonly InputAction m_Player_FreeLook;
    private readonly InputAction m_Player_Alpha1;
    private readonly InputAction m_Player_Alpha2;
    private readonly InputAction m_Player_Alpha3;
    private readonly InputAction m_Player_Alpha4;
    private readonly InputAction m_Player_Alpha5;
    private readonly InputAction m_Player_Alpha6;
    private readonly InputAction m_Player_Inventory;
    private readonly InputAction m_Player_AutoRun;
    private readonly InputAction m_Player_FastWeaponTake;
    private readonly InputAction m_Player_FreeCursor;
    private readonly InputAction m_Player_ActiveAction;
    private readonly InputAction m_Player_SkillList;
    private readonly InputAction m_Player_Skill1;
    private readonly InputAction m_Player_Skill2;
    private readonly InputAction m_Player_Skill3;
    private readonly InputAction m_Player_Stats;
    private readonly InputAction m_Player_Attack;
    private readonly InputAction m_Player_Pose0;
    private readonly InputAction m_Player_Pose1;
    private readonly InputAction m_Player_Pose2;
    public struct PlayerActions
    {
        private @MainInput m_Wrapper;
        public PlayerActions(@MainInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @Sprint => m_Wrapper.m_Player_Sprint;
        public InputAction @Look => m_Wrapper.m_Player_Look;
        public InputAction @Zoom => m_Wrapper.m_Player_Zoom;
        public InputAction @Walk => m_Wrapper.m_Player_Walk;
        public InputAction @Dash => m_Wrapper.m_Player_Dash;
        public InputAction @FreeLook => m_Wrapper.m_Player_FreeLook;
        public InputAction @Alpha1 => m_Wrapper.m_Player_Alpha1;
        public InputAction @Alpha2 => m_Wrapper.m_Player_Alpha2;
        public InputAction @Alpha3 => m_Wrapper.m_Player_Alpha3;
        public InputAction @Alpha4 => m_Wrapper.m_Player_Alpha4;
        public InputAction @Alpha5 => m_Wrapper.m_Player_Alpha5;
        public InputAction @Alpha6 => m_Wrapper.m_Player_Alpha6;
        public InputAction @Inventory => m_Wrapper.m_Player_Inventory;
        public InputAction @AutoRun => m_Wrapper.m_Player_AutoRun;
        public InputAction @FastWeaponTake => m_Wrapper.m_Player_FastWeaponTake;
        public InputAction @FreeCursor => m_Wrapper.m_Player_FreeCursor;
        public InputAction @ActiveAction => m_Wrapper.m_Player_ActiveAction;
        public InputAction @SkillList => m_Wrapper.m_Player_SkillList;
        public InputAction @Skill1 => m_Wrapper.m_Player_Skill1;
        public InputAction @Skill2 => m_Wrapper.m_Player_Skill2;
        public InputAction @Skill3 => m_Wrapper.m_Player_Skill3;
        public InputAction @Stats => m_Wrapper.m_Player_Stats;
        public InputAction @Attack => m_Wrapper.m_Player_Attack;
        public InputAction @Pose0 => m_Wrapper.m_Player_Pose0;
        public InputAction @Pose1 => m_Wrapper.m_Player_Pose1;
        public InputAction @Pose2 => m_Wrapper.m_Player_Pose2;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Sprint.started += instance.OnSprint;
            @Sprint.performed += instance.OnSprint;
            @Sprint.canceled += instance.OnSprint;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Zoom.started += instance.OnZoom;
            @Zoom.performed += instance.OnZoom;
            @Zoom.canceled += instance.OnZoom;
            @Walk.started += instance.OnWalk;
            @Walk.performed += instance.OnWalk;
            @Walk.canceled += instance.OnWalk;
            @Dash.started += instance.OnDash;
            @Dash.performed += instance.OnDash;
            @Dash.canceled += instance.OnDash;
            @FreeLook.started += instance.OnFreeLook;
            @FreeLook.performed += instance.OnFreeLook;
            @FreeLook.canceled += instance.OnFreeLook;
            @Alpha1.started += instance.OnAlpha1;
            @Alpha1.performed += instance.OnAlpha1;
            @Alpha1.canceled += instance.OnAlpha1;
            @Alpha2.started += instance.OnAlpha2;
            @Alpha2.performed += instance.OnAlpha2;
            @Alpha2.canceled += instance.OnAlpha2;
            @Alpha3.started += instance.OnAlpha3;
            @Alpha3.performed += instance.OnAlpha3;
            @Alpha3.canceled += instance.OnAlpha3;
            @Alpha4.started += instance.OnAlpha4;
            @Alpha4.performed += instance.OnAlpha4;
            @Alpha4.canceled += instance.OnAlpha4;
            @Alpha5.started += instance.OnAlpha5;
            @Alpha5.performed += instance.OnAlpha5;
            @Alpha5.canceled += instance.OnAlpha5;
            @Alpha6.started += instance.OnAlpha6;
            @Alpha6.performed += instance.OnAlpha6;
            @Alpha6.canceled += instance.OnAlpha6;
            @Inventory.started += instance.OnInventory;
            @Inventory.performed += instance.OnInventory;
            @Inventory.canceled += instance.OnInventory;
            @AutoRun.started += instance.OnAutoRun;
            @AutoRun.performed += instance.OnAutoRun;
            @AutoRun.canceled += instance.OnAutoRun;
            @FastWeaponTake.started += instance.OnFastWeaponTake;
            @FastWeaponTake.performed += instance.OnFastWeaponTake;
            @FastWeaponTake.canceled += instance.OnFastWeaponTake;
            @FreeCursor.started += instance.OnFreeCursor;
            @FreeCursor.performed += instance.OnFreeCursor;
            @FreeCursor.canceled += instance.OnFreeCursor;
            @ActiveAction.started += instance.OnActiveAction;
            @ActiveAction.performed += instance.OnActiveAction;
            @ActiveAction.canceled += instance.OnActiveAction;
            @SkillList.started += instance.OnSkillList;
            @SkillList.performed += instance.OnSkillList;
            @SkillList.canceled += instance.OnSkillList;
            @Skill1.started += instance.OnSkill1;
            @Skill1.performed += instance.OnSkill1;
            @Skill1.canceled += instance.OnSkill1;
            @Skill2.started += instance.OnSkill2;
            @Skill2.performed += instance.OnSkill2;
            @Skill2.canceled += instance.OnSkill2;
            @Skill3.started += instance.OnSkill3;
            @Skill3.performed += instance.OnSkill3;
            @Skill3.canceled += instance.OnSkill3;
            @Stats.started += instance.OnStats;
            @Stats.performed += instance.OnStats;
            @Stats.canceled += instance.OnStats;
            @Attack.started += instance.OnAttack;
            @Attack.performed += instance.OnAttack;
            @Attack.canceled += instance.OnAttack;
            @Pose0.started += instance.OnPose0;
            @Pose0.performed += instance.OnPose0;
            @Pose0.canceled += instance.OnPose0;
            @Pose1.started += instance.OnPose1;
            @Pose1.performed += instance.OnPose1;
            @Pose1.canceled += instance.OnPose1;
            @Pose2.started += instance.OnPose2;
            @Pose2.performed += instance.OnPose2;
            @Pose2.canceled += instance.OnPose2;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Sprint.started -= instance.OnSprint;
            @Sprint.performed -= instance.OnSprint;
            @Sprint.canceled -= instance.OnSprint;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Zoom.started -= instance.OnZoom;
            @Zoom.performed -= instance.OnZoom;
            @Zoom.canceled -= instance.OnZoom;
            @Walk.started -= instance.OnWalk;
            @Walk.performed -= instance.OnWalk;
            @Walk.canceled -= instance.OnWalk;
            @Dash.started -= instance.OnDash;
            @Dash.performed -= instance.OnDash;
            @Dash.canceled -= instance.OnDash;
            @FreeLook.started -= instance.OnFreeLook;
            @FreeLook.performed -= instance.OnFreeLook;
            @FreeLook.canceled -= instance.OnFreeLook;
            @Alpha1.started -= instance.OnAlpha1;
            @Alpha1.performed -= instance.OnAlpha1;
            @Alpha1.canceled -= instance.OnAlpha1;
            @Alpha2.started -= instance.OnAlpha2;
            @Alpha2.performed -= instance.OnAlpha2;
            @Alpha2.canceled -= instance.OnAlpha2;
            @Alpha3.started -= instance.OnAlpha3;
            @Alpha3.performed -= instance.OnAlpha3;
            @Alpha3.canceled -= instance.OnAlpha3;
            @Alpha4.started -= instance.OnAlpha4;
            @Alpha4.performed -= instance.OnAlpha4;
            @Alpha4.canceled -= instance.OnAlpha4;
            @Alpha5.started -= instance.OnAlpha5;
            @Alpha5.performed -= instance.OnAlpha5;
            @Alpha5.canceled -= instance.OnAlpha5;
            @Alpha6.started -= instance.OnAlpha6;
            @Alpha6.performed -= instance.OnAlpha6;
            @Alpha6.canceled -= instance.OnAlpha6;
            @Inventory.started -= instance.OnInventory;
            @Inventory.performed -= instance.OnInventory;
            @Inventory.canceled -= instance.OnInventory;
            @AutoRun.started -= instance.OnAutoRun;
            @AutoRun.performed -= instance.OnAutoRun;
            @AutoRun.canceled -= instance.OnAutoRun;
            @FastWeaponTake.started -= instance.OnFastWeaponTake;
            @FastWeaponTake.performed -= instance.OnFastWeaponTake;
            @FastWeaponTake.canceled -= instance.OnFastWeaponTake;
            @FreeCursor.started -= instance.OnFreeCursor;
            @FreeCursor.performed -= instance.OnFreeCursor;
            @FreeCursor.canceled -= instance.OnFreeCursor;
            @ActiveAction.started -= instance.OnActiveAction;
            @ActiveAction.performed -= instance.OnActiveAction;
            @ActiveAction.canceled -= instance.OnActiveAction;
            @SkillList.started -= instance.OnSkillList;
            @SkillList.performed -= instance.OnSkillList;
            @SkillList.canceled -= instance.OnSkillList;
            @Skill1.started -= instance.OnSkill1;
            @Skill1.performed -= instance.OnSkill1;
            @Skill1.canceled -= instance.OnSkill1;
            @Skill2.started -= instance.OnSkill2;
            @Skill2.performed -= instance.OnSkill2;
            @Skill2.canceled -= instance.OnSkill2;
            @Skill3.started -= instance.OnSkill3;
            @Skill3.performed -= instance.OnSkill3;
            @Skill3.canceled -= instance.OnSkill3;
            @Stats.started -= instance.OnStats;
            @Stats.performed -= instance.OnStats;
            @Stats.canceled -= instance.OnStats;
            @Attack.started -= instance.OnAttack;
            @Attack.performed -= instance.OnAttack;
            @Attack.canceled -= instance.OnAttack;
            @Pose0.started -= instance.OnPose0;
            @Pose0.performed -= instance.OnPose0;
            @Pose0.canceled -= instance.OnPose0;
            @Pose1.started -= instance.OnPose1;
            @Pose1.performed -= instance.OnPose1;
            @Pose1.canceled -= instance.OnPose1;
            @Pose2.started -= instance.OnPose2;
            @Pose2.performed -= instance.OnPose2;
            @Pose2.canceled -= instance.OnPose2;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
        void OnWalk(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnFreeLook(InputAction.CallbackContext context);
        void OnAlpha1(InputAction.CallbackContext context);
        void OnAlpha2(InputAction.CallbackContext context);
        void OnAlpha3(InputAction.CallbackContext context);
        void OnAlpha4(InputAction.CallbackContext context);
        void OnAlpha5(InputAction.CallbackContext context);
        void OnAlpha6(InputAction.CallbackContext context);
        void OnInventory(InputAction.CallbackContext context);
        void OnAutoRun(InputAction.CallbackContext context);
        void OnFastWeaponTake(InputAction.CallbackContext context);
        void OnFreeCursor(InputAction.CallbackContext context);
        void OnActiveAction(InputAction.CallbackContext context);
        void OnSkillList(InputAction.CallbackContext context);
        void OnSkill1(InputAction.CallbackContext context);
        void OnSkill2(InputAction.CallbackContext context);
        void OnSkill3(InputAction.CallbackContext context);
        void OnStats(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnPose0(InputAction.CallbackContext context);
        void OnPose1(InputAction.CallbackContext context);
        void OnPose2(InputAction.CallbackContext context);
    }
}
